version: '3.8'

# service stack for RTE-RRTMGP Continuous Integration
# images depend on each other, but docker-compose only has a "depends_on"
# option for running the services (i.e., running the container)
# https://stackoverflow.com/a/37945466
# so one either has to build the images at the beginning of the
# chain or build them first
services:
  min-oneapi:
    build:
      context: ./
      dockerfile: Dockerfile-oneapi-minimal
    image: minimal-toolchain:oneapi
    container_name: min-oneapi

  min-nvhpc:
    build:
      context: ./
      dockerfile: Dockerfile-nvhpc-minimal
    image: minimal-toolchain:nvhpc
    container_name: min-nvhpc

  nc-oneapi:
    build:
      context: ./
      dockerfile: Dockerfile-add-netcdf
      args:
        - TOOLCHAIN=oneapi
    image: add-netcdf:oneapi
    container_name: nc-oneapi

  nc-nvhpc:
    build:
      context: ./
      dockerfile: Dockerfile-add-netcdf
      args:
        - TOOLCHAIN=nvhpc
    image: add-netcdf:nvhpc
    container_name: nc-nvhpc

  py-oneapi:
    build:
      context: ./
      dockerfile: Dockerfile-add-python
      args:
        - TOOLCHAIN=oneapi
    image: add-python:oneapi
    container_name: py-oneapi

  py-nvhpc:
    build:
      context: ./
      dockerfile: Dockerfile-add-python
      args:
        - TOOLCHAIN=nvhpc
    image: add-python:nvhpc
    container_name: py-nvhpc

  ci-oneapi:
    build:
      context: ./
      dockerfile: Dockerfile-finalize
      args:
        - TOOLCHAIN=oneapi
    image: earthsystemradiation/rte-rrtmgp-ci:oneapi
    container_name: ci-oneapi

  ci-nvhpc:
    build:
      context: ./
      dockerfile: Dockerfile-finalize
      args:
        - TOOLCHAIN=nvhpc
    image: earthsystemradiation/rte-rrtmgp-ci:nvhpc
    container_name: ci-nvhpc
