name: RRTMGP Base Images Build
run-name: CI Image Build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # - name: Check out repository code
      #   uses: actions/checkout@https://github.com/earth-system-radiation/containers.git
      - name: List Dockerfiles
        run: ls *
