name: RRTMGP Base Images Build
run-name: CI Image Build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@6d919c30728dab8f9e76511bf71d8395d1ceaf91
      - name: List Dockerfiles
        run: ls Dockerfile*
