name: RRTMGP Base Images Build
run-name: CI Image Build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        run: |
          docker build . -t minimal-compiler:ifort -f Dockerfile-ifort-minimal
          docker build . -t add-netcdf:ifort -f Dockerfile-add-netcdf --build-arg COMPILER=ifort
          docker build . -t rte-rrtmgp-ci:ifort -f Dockerfile-add-python --build-arg COMPILER=ifort
          docker tag rte-rrtmgp-ci:ifort earthsystemradiation/rte-rrtmgp-ci:ifort
          docker push earthsystemradiation/rte-rrtmgp-ci:ifort
