name: RRTMGP Base Images Build
run-name: CI Image Build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: earth-system-radiation/containers@40c769b45cd6cb283623a701f9387152873da267
      - name: List Dockerfiles
        run: ls *
