# simplified and modified from https://github.com/marketplace/actions/build-and-push-docker-images#git-context
name: RRTMGP Base Images Build

on:
  push:
    branches:
      - 'cicd'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: user/app:latest
